name: Bug report
description: Décrire un dysfonctionnement
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: context
    attributes:
      label: Contexte
      placeholder: Qu'essayais-tu de faire ?
    validations: { required: true }
  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      placeholder: 1. … 2. …
    validations: { required: true }
