name: ci-test
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CI running
        run: echo "Test GitHub Actions"
